import { promises as fs } from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';

export class BuilderEngine {
  constructor({workspace,maxFiles=200,maxBuildRounds=3}={}){this.workspace=workspace;this.maxFiles=maxFiles;this.maxBuildRounds=maxBuildRounds;}
  async inspect(id){const files=await this.workspace.inspect(id);if(files.length>this.maxFiles)throw new Error('Workspace exceeds NOVA builder file limit.');const counts={};for(const f of files)counts[f.extension||'[no extension]']=(counts[f.extension||'[no extension]']||0)+1;return{files,counts,fileCount:files.length};}
  async syntaxCheck(id,rel){const ext=path.extname(rel).toLowerCase();if(!['.js','.mjs','.cjs'].includes(ext))return{path:rel,runner:'none',checked:false,ok:true,reason:'syntax checker not applicable'};return this.runSafe(id,process.execPath,['--check',this.workspace.filePath(id,rel)]).then(r=>({path:rel,runner:'node --check',checked:true,ok:r.ok,detail:r.stderr||r.stdout||null}));}
  async runSafe(id,command,args){const allowed=new Set([process.execPath,'python3','python']);const base=path.basename(command);if(command!==process.execPath&&!['python3','python'].includes(base))throw new Error('Runner not allowlisted.');return new Promise(resolve=>{const child=spawn(command,args,{cwd:this.workspace.workspacePath(id),stdio:['ignore','pipe','pipe'],shell:false});let stdout='',stderr='';child.stdout.on('data',d=>stdout+=d);child.stderr.on('data',d=>stderr+=d);child.on('close',code=>resolve({ok:code===0,code,stdout:stdout.trim(),stderr:stderr.trim()}));child.on('error',e=>resolve({ok:false,code:null,stdout:'',stderr:e.message}));});}
  async test(id){const files=await this.workspace.inspect(id);const checks=[];for(const f of files.filter(x=>['.js','.mjs','.cjs'].includes(x.extension)).slice(0,this.maxFiles))checks.push(await this.syntaxCheck(id,f.path));const py=files.filter(x=>x.extension==='.py').slice(0,20);for(const f of py){const r=await this.runSafe(id,process.platform==='win32'?'python':'python3',['-m','py_compile',this.workspace.filePath(id,f.path)]);checks.push({path:f.path,runner:'python py_compile',checked:true,ok:r.ok,detail:r.stderr||r.stdout||null});}const html=files.filter(x=>['.html','.htm'].includes(x.extension)).slice(0,20);for(const f of html){const c=await this.workspace.read(id,f.path);checks.push({path:f.path,runner:'html-structural',checked:true,ok:/<html[\s>]/i.test(c)&&/<\/html>/i.test(c),detail:/<html[\s>]/i.test(c)&&/<\/html>/i.test(c)?null:'Missing <html> root or closing tag'});}return{ok:checks.every(x=>x.ok),checks,checked:checks.length};}
  async buildPlan(id,goal){const info=await this.inspect(id);return{goal:String(goal||'').trim(),workspace:id,stages:['understand','inspect','plan','review','apply','test','diagnose','repair','verify','package'],discoveredFiles:info.fileCount,note:'NOVA Builder uses sandboxed workspaces and strict allowlisted verification runners.'};}
  async applyChanges(id,changes,{overwrite=true}={}){if(!Array.isArray(changes)||!changes.length)throw new Error('At least one file change is required.');if(changes.length>this.maxFiles)throw new Error('Change set exceeds NOVA builder file limit.');const applied=[];for(const c of changes){if(!c||typeof c.path!=='string')throw new Error('Every change requires a path.');if(typeof c.content!=='string')throw new Error(`Missing string content for ${c.path}.`);applied.push(await this.workspace.write(id,c.path,c.content,{overwrite}));}return applied;}
  async snapshot(id){const files=await this.workspace.inspect(id);const contents=[];for(const f of files)contents.push({path:f.path,content:await this.workspace.read(id,f.path)});return contents;}
  async restore(id,snapshot){const current=await this.workspace.inspect(id),wanted=new Set(snapshot.map(x=>x.path));for(const f of current)if(!wanted.has(f.path))await this.workspace.remove(id,f.path);for(const item of snapshot)await this.workspace.write(id,item.path,item.content,{overwrite:true});return{restored:snapshot.length};}
  diagnose(testResult){return(testResult?.checks||[]).filter(x=>!x.ok).map(f=>({path:f.path,detail:f.detail,category:/SyntaxError|Unexpected token|Missing <html>/i.test(String(f.detail))?'syntax/structure':'verification'}));}
  async autonomousBuild(id,{goal='',changes=[],repair}={}){const before=await this.snapshot(id),trace=[];let round=0,applied=[];try{trace.push({stage:'inspect',result:await this.inspect(id)});if(changes.length){applied=await this.applyChanges(id,changes);trace.push({stage:'apply',changes:applied});}while(round<this.maxBuildRounds){round++;const test=await this.test(id);trace.push({stage:'test',round,result:test});if(test.ok){const artifact=await this.workspace.package(id),finalInspect=await this.inspect(id);if(typeof this.workspace.updateManifest==='function'){const manifest=typeof this.workspace.readManifest==='function'?await this.workspace.readManifest(id):{history:[]};await this.workspace.updateManifest(id,{goal,updatedAt:new Date().toISOString(),lastBuild:{ok:true,rounds:round,changed:applied,tests:test,artifactSha256:artifact.sha256},history:[...(manifest.history||[]),{at:new Date().toISOString(),goal,ok:true,rounds:round,artifactSha256:artifact.sha256}].slice(-50)});}return{ok:true,goal,rounds:round,applied,trace,artifact,inspect:finalInspect};}const diagnosis=this.diagnose(test);trace.push({stage:'diagnose',round,diagnosis});if(typeof repair!=='function'||round>=this.maxBuildRounds)break;const repairResult=await repair({goal,diagnosis,test,round,inspect:await this.inspect(id)});if(!repairResult?.changes?.length)break;const repaired=await this.applyChanges(id,repairResult.changes);applied.push(...repaired);trace.push({stage:'repair',round,changes:repaired});}const finalTest=await this.test(id);trace.push({stage:'rollback',reason:'verification-failed'});await this.restore(id,before);if(typeof this.workspace.updateManifest==='function')await this.workspace.updateManifest(id,{goal,updatedAt:new Date().toISOString(),lastBuild:{ok:false,rounds:round,tests:finalTest,rolledBack:true}});return{ok:false,goal,rounds:round,applied,trace,inspect:await this.inspect(id),test:finalTest,rolledBack:true};}catch(error){if(!error.builderTrace){try{await this.restore(id,before);}catch{}error.builderTrace=trace;}throw error;}}
}
