import { promises as fs } from 'node:fs';
import path from 'node:path';
import { randomUUID, createHash } from 'node:crypto';
import AdmZip from 'adm-zip';

export class WorkspaceManager {
  constructor({ root = path.resolve(process.cwd(), 'workspaces'), maxFileBytes = 2 * 1024 * 1024 } = {}) {
    this.root = path.resolve(root); this.maxFileBytes = maxFileBytes;
  }
  async init() { await fs.mkdir(this.root, { recursive: true }); }
  safeWorkspaceId(id) { if (!/^[a-zA-Z0-9_-]{1,80}$/.test(String(id || ''))) throw new Error('Invalid workspace id.'); return String(id); }
  safeRelative(rel = '') { const value=String(rel).replaceAll('\\','/'); if(!value||value.includes('\0')||path.posix.isAbsolute(value)) throw new Error('Invalid relative path.'); const normalized=path.posix.normalize(value); if(normalized==='..'||normalized.startsWith('../')) throw new Error('Path traversal blocked.'); return normalized; }
  workspacePath(id) { return path.join(this.root, this.safeWorkspaceId(id)); }
  filePath(id, rel) { return path.join(this.workspacePath(id), this.safeRelative(rel)); }
  async create(name='nova-project') { const id=`${String(name).toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,48)||'workspace'}-${randomUUID().slice(0,8)}`; await fs.mkdir(this.workspacePath(id),{recursive:true}); await this.writeManifest(id,{id,name,createdAt:new Date().toISOString(),version:1,goal:null,history:[]}); return {id,name,path:this.workspacePath(id)}; }
  async exists(id){try{await fs.access(this.workspacePath(id));return true;}catch{return false;}}
  async ensure(id){if(!(await this.exists(id)))throw new Error('Workspace not found.');}
  async list(id,rel='.') { await this.ensure(id); const base=rel==='.'?this.workspacePath(id):this.filePath(id,rel); const entries=await fs.readdir(base,{withFileTypes:true}); return entries.filter(e=>!['.nova-workspace.json','.nova'].includes(e.name)).map(e=>({name:e.name,type:e.isDirectory()?'directory':'file',path:path.posix.join(rel==='.'?'':this.safeRelative(rel),e.name)})); }
  async read(id,rel){await this.ensure(id);const file=this.filePath(id,rel);const stat=await fs.stat(file);if(!stat.isFile())throw new Error('Target is not a file.');if(stat.size>this.maxFileBytes)throw new Error('File exceeds NOVA workspace read limit.');return fs.readFile(file,'utf8');}
  async write(id,rel,content,{overwrite=false}={}){await this.ensure(id);const file=this.filePath(id,rel);const data=String(content??'');if(Buffer.byteLength(data)>this.maxFileBytes)throw new Error('File exceeds NOVA workspace write limit.');try{await fs.access(file);if(!overwrite)throw new Error('File exists; explicit overwrite is required.');}catch(e){if(e.code!=='ENOENT')throw e;}await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,data,'utf8');return{path:this.safeRelative(rel),bytes:Buffer.byteLength(data)};}
  async remove(id,rel){await this.ensure(id);const target=this.filePath(id,rel);const stat=await fs.stat(target).catch(()=>null);if(!stat)throw new Error('Target not found.');if(stat.isDirectory())throw new Error('Directory deletion requires explicit folder operation.');await fs.rm(target);return{path:this.safeRelative(rel),removed:true};}
  async move(id,from,to){await this.ensure(id);const src=this.filePath(id,from),dst=this.filePath(id,to);if(src===dst)throw new Error('Source and destination are identical.');await fs.mkdir(path.dirname(dst),{recursive:true});try{await fs.access(dst);throw new Error('Destination exists; choose another path.');}catch(e){if(e.code!=='ENOENT')throw e;}await fs.rename(src,dst);return{from:this.safeRelative(from),to:this.safeRelative(to)};}
  async patch(id,rel,find,replace,{all=false}={}){const current=await this.read(id,rel),needle=String(find);if(!needle)throw new Error('Patch find text is required.');const count=current.split(needle).length-1;if(!count)throw new Error('Patch target not found.');if(!all&&count>1)throw new Error('Patch target is ambiguous; set all=true or provide a more specific target.');const next=all?current.split(needle).join(String(replace)):current.replace(needle,String(replace));return{...(await this.write(id,rel,next,{overwrite:true})),replacements:all?count:1};}
  async inspect(id){await this.ensure(id);const out=[];const walk=async(dir,rel='')=>{for(const e of await fs.readdir(dir,{withFileTypes:true})){if(e.name==='.nova-workspace.json'||e.name==='.git'||e.name==='.nova')continue;const rp=path.posix.join(rel,e.name);if(e.isDirectory())await walk(path.join(dir,e.name),rp);else{const st=await fs.stat(path.join(dir,e.name));out.push({path:rp,size:st.size,extension:path.extname(e.name).toLowerCase()});}}};await walk(this.workspacePath(id));return out.sort((a,b)=>a.path.localeCompare(b.path));}
  async manifestPath(id){await this.ensure(id);const dir=path.join(this.workspacePath(id),'.nova');await fs.mkdir(dir,{recursive:true});return path.join(dir,'manifest.json');}
  async readManifest(id){const p=await this.manifestPath(id);try{return JSON.parse(await fs.readFile(p,'utf8'));}catch{return{version:1,history:[]};}}
  async writeManifest(id,data){await this.ensure(id);const dir=path.join(this.workspacePath(id),'.nova');await fs.mkdir(dir,{recursive:true});const p=path.join(dir,'manifest.json');await fs.writeFile(p,JSON.stringify(data,null,2),'utf8');return data;}
  async updateManifest(id,patch){const current=await this.readManifest(id);const next={...current,...patch};await this.writeManifest(id,next);return next;}
  async importZip(id,zipPath){await this.ensure(id);const zip=new AdmZip(zipPath);const entries=zip.getEntries();let imported=0;for(const entry of entries){if(entry.isDirectory)continue;const rel=this.safeRelative(entry.entryName);if(rel.startsWith('.git/')||rel==='.nova-workspace.json'||rel.startsWith('.nova/'))continue;const data=entry.getData();if(data.length>this.maxFileBytes)continue;await this.write(id,rel,data.toString('utf8'),{overwrite:true});imported++;}return{imported};}
  async package(id){await this.ensure(id);const zip=new AdmZip();const files=await this.inspect(id);for(const f of files)zip.addLocalFile(this.filePath(id,f.path),path.posix.dirname(f.path)==='.'?'':path.posix.dirname(f.path));const out=path.join(this.root,`${id}-artifact.zip`);zip.writeZip(out);const data=await fs.readFile(out);return{path:out,files:files.length,sha256:createHash('sha256').update(data).digest('hex'),bytes:data.length};}
}
